application: koushanet
version: 1
runtime: go
api_version: go1

handlers:
- url: /css
  static_dir: css

- url: /font
  static_dir: font

- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /index.html
  static_files: index.html
  upload: index.html

- url: /keybase.txt
  static_files: keybase.txt
  upload: keybase.txt

- url: /.*
  script: _go_app
